export const siteConfig = {
  names: {
    groom: 'Chico',
    bride: 'Alexita',
  },
  eventDate: '2027-03-06T17:00:00', // Reference date for general countdown
  theme: {
    colors: {
      background: '#faf8f5', // Warm off-white
      foreground: '#222222', // Charcoal
      primary: '#d4a373',    // Configurable primary (sand/beige)
      accent: '#e9edc9',     // Soft accent
    },
    fonts: {
      heading: 'var(--font-playfair)',
      body: 'var(--font-inter)',
    },
  },
  // Detailed Event Information
  events: {
    ar: {
      id: 'argentina',
      title: 'Argentina',
      dateTime: '2027-02-20T11:00:00',
      locationName: 'Club de Campo San Diego',
      address: 'Au Acceso Oeste Km 42, B1744 Moreno, Provincia de Buenos Aires, Argentina',
      mapLink: 'https://www.google.com/maps/place/Club+de+Campo+San+Diego/@-34.6147323,-58.8543517,17z/data=!3m1!4b1!4m6!3m5!1s0x95bc9437abeabf2b:0xd3205ac9847354cf!8m2!3d-34.6147323!4d-58.8517768!16s%2Fg%2F11tk8ps8f?entry=ttu',
    },
    br: {
      id: 'brasil',
      title: 'Brasil',
      dateTime: '2027-03-06T16:00:00',
      locationName: 'Hotel Boutique & Spa Ponta de Inhambupe',
      address: 'Loteamento Ponta de Inhambupe, 189 - Baixio, Esplanada - BA, 48370-000, Brasil',
      mapLink: 'https://www.google.com/maps/place/Hotel+Boutique+%26+Spa+Ponta+de+Inhambupe+by+Slaviero+Hot%C3%A9is/@-12.1023221,-37.6930429,17z/data=!3m1!4b1!4m9!3m8!1s0x717376dd6887931:0x6d4526a6d0ab8dea!5m2!4m1!1i2!8m2!3d-12.1023221!4d-37.690468!16s%2Fg%2F11pdxwrbyd?entry=ttu',
    },
  },
  // Centralized Gift Registry
  gifts: [
    {
      id: 1,
      category: { br: 'Experiência', ar: 'Experiencia', en: 'Experience' },
      localized: {
        br: { name: 'Jantar Romântico em Buenos Aires', description: 'Um jantar especial para o casal.', price: 500 },
        ar: { name: 'Cena Romántica en Buenos Aires', description: 'Una cena especial para la pareja.', price: 15000 },
        en: { name: 'Romantic Dinner in Buenos Aires', description: 'A special dinner for the couple.', price: 100 },
      },
    },
    {
      id: 2,
      category: { br: 'Viagem', ar: 'Viaje', en: 'Travel' },
      localized: {
        br: { name: 'Passagens Aéreas', description: 'Ajude-nos a chegar ao nuestro destino.', price: 2000 },
        ar: { name: 'Pasajes Aéreos', description: 'Ayúdanos a llegar a nuestro destino.', price: 60000 },
        en: { name: 'Flight Tickets', description: 'Help us reach our destination.', price: 400 },
      },
    },
    {
      id: 3,
      category: { br: 'Viagem', ar: 'Viaje', en: 'Travel' },
      localized: {
        br: { name: 'Hospedagem em Resort', description: 'Uma noite de descanso e luxo.', price: 800 },
        ar: { name: 'Estadía en Resort', description: 'Una noche de descanso y lujo.', price: 25000 },
        en: { name: 'Resort Stay', description: 'A night of rest and luxury.', price: 150 },
      },
    },
    {
      id: 4,
      category: { br: 'Experiência', ar: 'Experiencia', en: 'Experience' },
      localized: {
        br: { name: 'Passeio de Barco', description: 'Explorando as águas cristalinas.', price: 300 },
        ar: { name: 'Paseo en Barco', description: 'Explorando las aguas cristalinas.', price: 10000 },
        en: { name: 'Boat Trip', description: 'Exploring crystalline waters.', price: 60 },
      },
    },
    {
      id: 5,
      category: { br: 'Casa', ar: 'Casa', en: 'Home' },
      localized: {
        br: { name: 'Jogo de Pratos', description: 'Para nossa nova casa.', price: 250 },
        ar: { name: 'Juego de Platos', description: 'Para nuestra nueva casa.', price: 8000 },
        en: { name: 'Dinnerware Set', description: 'For our new home.', price: 50 },
      },
    },
    {
      id: 6,
      category: { br: 'Casa', ar: 'Casa', en: 'Home' },
      localized: {
        br: { name: 'Cafeteira Espresso', description: 'Para começar o dia bem.', price: 100 },
        ar: { name: 'Cafetera Espresso', description: 'Para empezar bien el día.', price: 50000 },
        en: { name: 'Espresso Machine', description: 'To start the day right.', price: 120 },
      },
    },
  ],
  // Travel tips — destinations to suggest to guests visiting northeast Brazil.
  // Distances are relative to the BR venue (Hotel Ponta de Inhambupe, Esplanada-BA).
  travelTips: [
    {
      id: 'praia-do-forte',
      reelUrl: 'https://www.instagram.com/reel/CZmlopxFhbT/',
      mapLink: 'https://www.google.com/maps/place/Praia+do+Forte,+Mata+de+S%C3%A3o+Jo%C3%A3o+-+State+of+Bahia',
      localized: {
        br: {
          name: 'Praia do Forte',
          blurb: 'Vila litorânea charmosa, sede do Projeto Tamar e com praias tranquilas de água quente.',
          distance: '≈ 1h de carro',
          highlights: 'Projeto Tamar (santuário de tartarugas), ruínas do Castelo Garcia d’Ávila, Alameda do Sol e piscinas naturais na maré baixa.',
          stay: 'Tivoli Ecoresort (5★ all-inclusive) ou pousadas charmosas na vila, como a Pousada João Sol.',
          budget: 'R$ 500–900',
        },
        ar: {
          name: 'Praia do Forte',
          blurb: 'Pueblito costero con encanto, sede del Projeto Tamar (tortugas marinas) y playas tranquilas.',
          distance: '≈ 1h en auto',
          highlights: 'Projeto Tamar (santuario de tortugas), ruinas del Castelo Garcia d’Ávila, Alameda do Sol y piscinas naturales con marea baja.',
          stay: 'Tivoli Ecoresort (5★ all-inclusive) o posadas con encanto en el pueblo, como Pousada João Sol.',
          budget: 'R$ 500–900',
        },
        en: {
          name: 'Praia do Forte',
          blurb: 'Charming coastal village with the Tamar sea-turtle sanctuary and warm, quiet beaches.',
          distance: '≈ 1h drive',
          highlights: 'Tamar sea-turtle sanctuary, the Garcia d’Ávila castle ruins, the Alameda do Sol pedestrian street, and tide pools at low tide.',
          stay: 'Tivoli Ecoresort (5★ all-inclusive) or charming village pousadas like Pousada João Sol.',
          budget: 'R$ 500–900',
        },
      },
    },
    {
      id: 'aracaju',
      reelUrl: 'https://www.instagram.com/reel/DOZUTlzEWZU/',
      mapLink: 'https://www.google.com/maps/place/Aracaju,+State+of+Sergipe',
      localized: {
        br: {
          name: 'Aracaju',
          blurb: 'Capital de Sergipe com praias urbanas tranquilas, a Orla de Atalaia e a charmosa Praia da Caueira.',
          distance: '≈ 2h30 de carro',
          highlights: 'Orla de Atalaia (4,6 km de calçadão), Mercado Central, bate-volta aos Cânions do Xingó e a calma Praia da Caueira.',
          stay: 'Radisson Aracaju (moderno, na Orla) ou Quinta do Sobrado Boutique para algo mais íntimo.',
          budget: 'R$ 350–600',
        },
        ar: {
          name: 'Aracaju',
          blurb: 'Capital de Sergipe con playas urbanas tranquilas, la Orla de Atalaia y la encantadora Praia da Caueira.',
          distance: '≈ 2h30 en auto',
          highlights: 'Orla de Atalaia (4,6 km de rambla), Mercado Central, excursión a los Cañones de Xingó y la tranquila Praia da Caueira.',
          stay: 'Radisson Aracaju (moderno, sobre la Orla) o Quinta do Sobrado Boutique para algo más íntimo.',
          budget: 'R$ 350–600',
        },
        en: {
          name: 'Aracaju',
          blurb: 'Sergipe’s capital — calm urban beaches, the Atalaia boardwalk, and the lovely Caueira beach.',
          distance: '≈ 2h30 drive',
          highlights: 'The 4.6 km Atalaia boardwalk, Central Market, a day-trip to the Xingó canyons, and quiet Caueira beach.',
          stay: 'Radisson Aracaju (modern, on the seafront) or Quinta do Sobrado Boutique for something more intimate.',
          budget: 'R$ 350–600',
        },
      },
    },
    {
      id: 'morro-de-sao-paulo',
      reelUrl: 'https://www.instagram.com/reel/DTX3zCVD3fH/',
      mapLink: 'https://www.google.com/maps/place/Morro+de+S%C3%A3o+Paulo,+Cair%C3%BA+-+State+of+Bahia',
      localized: {
        br: {
          name: 'Morro de São Paulo',
          blurb: 'Ilha sem carros com praias numeradas paradisíacas, vida noturna e barcos saindo de Salvador.',
          distance: '≈ 4h (carro + barco)',
          highlights: 'As Quatro Praias numeradas (Segunda é a mais animada, Quarta é paradisíaca), tirolesa sobre a Primeira, pôr do sol na Toca do Morcego e snorkel nas piscinas naturais de Garapuá.',
          stay: 'Anima Hotel Boutique (Segunda Praia, adults-only) ou Vila dos Orixás (Quinta Praia, luxo isolado).',
          budget: 'R$ 600–1.100',
        },
        ar: {
          name: 'Morro de São Paulo',
          blurb: 'Isla sin autos, con playas paradisíacas numeradas, vida nocturna y catamaranes desde Salvador.',
          distance: '≈ 4h (auto + lancha)',
          highlights: 'Las Cuatro Playas numeradas (Segunda es la más movida, Cuarta es paradisíaca), tirolesa sobre la Primeira, atardecer en Toca do Morcego y snorkel en las piscinas naturales de Garapuá.',
          stay: 'Anima Hotel Boutique (Segunda Praia, solo adultos) o Vila dos Orixás (Quinta Praia, lujo aislado).',
          budget: 'R$ 600–1.100',
        },
        en: {
          name: 'Morro de São Paulo',
          blurb: 'Car-free island with numbered paradise beaches, lively nights, and boats from Salvador.',
          distance: '≈ 4h (drive + ferry)',
          highlights: 'The numbered beaches (Segunda is the social hub, Quarta is the paradise one), the Primeira-Praia zipline, sunset at Toca do Morcego, and snorkeling Garapuá’s natural pools.',
          stay: 'Anima Hotel Boutique (Segunda Praia, adults-only) or Vila dos Orixás (Quinta Praia, secluded luxury).',
          budget: 'R$ 600–1,100',
        },
      },
    },
    {
      id: 'maragogi',
      reelUrl: 'https://www.instagram.com/reel/DPquUfXjf87/',
      mapLink: 'https://www.google.com/maps/place/Maragogi,+State+of+Alagoas',
      localized: {
        br: {
          name: 'Maragogi',
          blurb: 'Conhecida como o Caribe brasileiro: piscinas naturais, recifes e águas cristalinas em Alagoas.',
          distance: '≈ 5h de carro',
          highlights: 'Catamarã às piscinas naturais dos Galés (6 km mar adentro — vá no primeiro horário), Praia do Toque, Praia de Antunes e passeio de jangada às Taocas com almoço de lagosta.',
          stay: 'Salinas Maragogi (all-inclusive clássico) ou Pousada Costa do Sol para algo pé-na-areia mais tranquilo.',
          budget: 'R$ 800–1.400',
        },
        ar: {
          name: 'Maragogi',
          blurb: 'Conocida como el Caribe brasileño: piscinas naturales, arrecifes y aguas cristalinas en Alagoas.',
          distance: '≈ 5h en auto',
          highlights: 'Catamarán a las piscinas naturales de Galés (6 km mar adentro — ir en el primer turno), Praia do Toque, Praia de Antunes y paseo en jangada a Taocas con almuerzo de langosta.',
          stay: 'Salinas Maragogi (all-inclusive clásico) o Pousada Costa do Sol para algo pie-en-la-arena más tranquilo.',
          budget: 'R$ 800–1.400',
        },
        en: {
          name: 'Maragogi',
          blurb: 'Known as Brazil’s Caribbean — natural pools, reefs, and crystal-clear waters in Alagoas.',
          distance: '≈ 5h drive',
          highlights: 'Catamaran to the Galés natural pools (6 km offshore — book the first slot), Praia do Toque, Praia de Antunes, and a jangada ride to Taocas for a lobster lunch.',
          stay: 'Salinas Maragogi (the classic all-inclusive resort) or Pousada Costa do Sol for a quieter feet-in-the-sand vibe.',
          budget: 'R$ 800–1,400',
        },
      },
    },
    {
      id: 'chapada-diamantina',
      reelUrl: 'https://www.instagram.com/reel/CZX5CeoFDCD/',
      mapLink: 'https://www.google.com/maps/place/Chapada+Diamantina+National+Park',
      localized: {
        br: {
          name: 'Chapada Diamantina',
          blurb: 'Parque nacional no interior baiano: cachoeiras, grutas, trilhas e paisagens de tirar o fôlego.',
          distance: '≈ 6h de carro',
          highlights: 'Poço Azul e Poço Encantado (feixes de luz nas águas azul-elétrico, abr–set), Cachoeira da Fumaça (340 m), Vale do Pati, pôr do sol no Morro do Pai Inácio e a vila de pedra de Lençóis como base.',
          stay: 'Pousada Vila Serrano (charme rústico em Lençóis) ou Hotel Canto das Águas (à beira-rio, mais conforto).',
          budget: 'R$ 350–600',
        },
        ar: {
          name: 'Chapada Diamantina',
          blurb: 'Parque nacional en el interior bahiano: cascadas, grutas, senderos y paisajes asombrosos.',
          distance: '≈ 6h en auto',
          highlights: 'Poço Azul y Poço Encantado (haces de luz sobre aguas azul-eléctrico, abr–sep), Cachoeira da Fumaça (340 m), Vale do Pati, atardecer en el Morro do Pai Inácio y el pueblito de piedra de Lençóis como base.',
          stay: 'Pousada Vila Serrano (encanto rústico en Lençóis) o Hotel Canto das Águas (al borde del río, más confort).',
          budget: 'R$ 350–600',
        },
        en: {
          name: 'Chapada Diamantina',
          blurb: 'Inland national park: waterfalls, caves, hiking trails, and breathtaking rock formations.',
          distance: '≈ 6h drive',
          highlights: 'Poço Azul and Poço Encantado (sunbeams turn the cave water electric blue, Apr–Sep), the 340 m Cachoeira da Fumaça, the Vale do Pati trek, sunset on Morro do Pai Inácio, and the cobblestone town of Lençóis as your base.',
          stay: 'Pousada Vila Serrano (rustic charm in Lençóis) or Hotel Canto das Águas (riverside, more comfort).',
          budget: 'R$ 350–600',
        },
      },
    },
    {
      id: 'porto-de-galinhas',
      reelUrl: 'https://www.instagram.com/reel/DPbcDtPjS8c/',
      mapLink: 'https://www.google.com/maps/place/Porto+de+Galinhas,+Ipojuca+-+State+of+Pernambuco',
      localized: {
        br: {
          name: 'Porto de Galinhas',
          blurb: 'Piscinas naturais transparentes, jangadas coloridas e o azul-verde mais icônico do nordeste pernambucano.',
          distance: '≈ 1h30 de avião + 1h de carro',
          highlights: 'Piscinas naturais de jangada na maré baixa (consulte a tábua de marés), pôr do sol no Pontal de Maracaípe com os cavalos-marinhos, surf na Praia de Maracaípe e a vida noturna da Rua da Esperança.',
          stay: 'Nannai Resort (5★ luxo pé-na-areia, bangalôs) ou Pousada Tabapitanga para um boutique aconchegante perto da vila.',
          budget: 'R$ 600–1.200',
        },
        ar: {
          name: 'Porto de Galinhas',
          blurb: 'Piscinas naturales cristalinas, jangadas coloridas y el verde-azulado más icónico del nordeste brasileño.',
          distance: '≈ 1h30 en avión + 1h en auto',
          highlights: 'Piscinas naturales en jangada con marea baja (consultá la tabla de mareas), atardecer en el Pontal de Maracaípe con los caballitos de mar, surf en Praia de Maracaípe y la noche en la Rua da Esperança.',
          stay: 'Nannai Resort (5★ lujo pie-en-la-arena, bungalows) o Pousada Tabapitanga para un boutique acogedor cerca del pueblo.',
          budget: 'R$ 600–1.200',
        },
        en: {
          name: 'Porto de Galinhas',
          blurb: 'Crystal-clear natural tide pools, colorful jangada rafts, and the most iconic turquoise waters of Pernambuco.',
          distance: '≈ 1h30 flight + 1h drive',
          highlights: 'Jangada rides to the natural tide pools at low tide (check the tide chart), sunset at Pontal de Maracaípe with the seahorses, surfing at Maracaípe beach, and nightlife along Rua da Esperança.',
          stay: 'Nannai Resort (5★ beachfront luxury bungalows) or Pousada Tabapitanga for a cozy boutique near the village.',
          budget: 'R$ 600–1,200',
        },
      },
    },
  ],
  // Region-specific configurations
  regions: {
    br: {
      region: 'br',
      label: 'Brasil',
      language: 'pt',
      currency: 'BRL',
      currencySymbol: 'R$',
      content: {
        welcomeTitle: 'Bem-vindos',
        welcomeText: 'Estamos muito felizes em compartilhar este momento tão especial com vocês.',
        giftListTitle: 'Lista de Presentes',
        giftButton: 'Presentear',
        cartTitle: 'Meu Carrinho',
        addMoreGifts: 'Adicionar mais presentes',
        continueCheckout: 'Continuar com a compra',
        gifterInfoTitle: 'Sua Mensagem',
        paymentTitle: 'Pagamento',
        orderSummary: 'Resumo do pedido',
        totalLabel: 'Total a pagar',
        successTitle: 'Pedido Confirmado!',
        backToSite: 'Voltar para o site',
        travelTipsTitle: 'Dicas de Viagem',
        travelTipsIntro: 'Sugestões para conhecer o Nordeste brasileiro durante a sua viagem.',
        travelMapButton: 'Ver no Mapa',
        travelLabelDistance: 'Distância',
        travelLabelHighlights: 'Não pode faltar',
        travelLabelStay: 'Onde ficar',
        travelLabelBudget: 'Orçamento / dia',
      },
    },
    ar: {
      region: 'ar',
      label: 'Argentina',
      language: 'es',
      currency: 'ARS',
      currencySymbol: '$',
      content: {
        welcomeTitle: 'Bienvenidos',
        welcomeText: 'Estamos muy felices de compartir este momento tan especial con ustedes.',
        giftListTitle: 'Lista de Regalos',
        giftButton: 'Regalar',
        cartTitle: 'Mi Carrito',
        addMoreGifts: 'Agregar más regalos',
        continueCheckout: 'Continuar con el regalo',
        gifterInfoTitle: 'Tu Mensaje',
        paymentTitle: 'Pago',
        orderSummary: 'Resumen del pedido',
        totalLabel: 'Total a pagar',
        successTitle: '¡Pedido Confirmado!',
        backToSite: 'Volver al sitio',
        travelTipsTitle: 'Tips de Viaje',
        travelTipsIntro: 'Sugerencias para descubrir el Nordeste brasileño durante el viaje.',
        travelMapButton: 'Ver en Mapa',
        travelLabelDistance: 'Distancia',
        travelLabelHighlights: 'Imperdible',
        travelLabelStay: 'Dónde alojarse',
        travelLabelBudget: 'Presupuesto / día',
      },
    },
    en: {
      region: 'en',
      label: 'International',
      language: 'en',
      currency: 'USD',
      currencySymbol: 'US$',
      content: {
        welcomeTitle: 'Welcome',
        welcomeText: 'We are very happy to share this special moment with you.',
        giftListTitle: 'Gift List',
        giftButton: 'Gift',
        cartTitle: 'My Cart',
        addMoreGifts: 'Add more gifts',
        continueCheckout: 'Continue to checkout',
        gifterInfoTitle: 'Your Message',
        paymentTitle: 'Payment',
        orderSummary: 'Order Summary',
        totalLabel: 'Total to pay',
        successTitle: 'Order Confirmed!',
        backToSite: 'Back to site',
        travelTipsTitle: 'Travel Tips',
        travelTipsIntro: 'Recommendations for exploring northeast Brazil while you’re here.',
        travelMapButton: 'View on Map',
        travelLabelDistance: 'Distance',
        travelLabelHighlights: 'Don’t miss',
        travelLabelStay: 'Where to stay',
        travelLabelBudget: 'Budget / day',
      },
    },
  },
  // Bank details for manual transfers
  bankDetails: {
    ar: {
      ars: {
        label: 'Pesos (ARS)',
        bank: 'Banco Galicia',
        alias: 'boda.alexita.chico',
        cbu: '0070000000000000000000',
        holder: 'Alexita & Chico',
      },
      usd: {
        label: 'Dólares (USD)',
        bank: 'Banco Galicia',
        alias: 'boda.usd.alexita',
        cbu: '0070000000000000000001',
        holder: 'Alexita & Chico',
      },
    },
  },
};
